language: python
addons:
  postgresql: "9.6"
services:
  - postgresql
python:
  - "3.6"
install:
  - pip install pipenv
  - pip install django-debug-toolbar
  - pip install coveralls
  - pipenv install --dev
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls