# Generated by Django 2.0.4 on 2018-04-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityjournal',
            name='time_lapse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityjournal',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 15, 58, 34, 603734)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 15, 58, 34, 605193)),
        ),
    ]
