# Generated by Django 2.0.4 on 2018-04-30 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180418_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 13, 20, 22, 694921)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 13, 20, 22, 695705)),
        ),
    ]
