# Generated by Django 2.0.4 on 2018-04-30 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180430_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 13, 24, 59, 476612)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 13, 24, 59, 488898)),
        ),
    ]
